# Generated by Django 3.1.4 on 2021-01-03 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_mhs',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('nim_tpb', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nim_jurusan', models.IntegerField()),
                ('angkatan', models.IntegerField()),
                ('fakultas', models.CharField(max_length=80)),
                ('jurusan', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='email_mhs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('nim_tpb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsite.data_mhs')),
            ],
        ),
    ]
